language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0
sudo: false
addons:
  postgresql: '9.5'
notifications:
  email: false
env:
  - MIX_ENV=test
before_script:
  - cp config/travis_ci_test.exs config/test.secret.exs
  - mix do ecto.create, ecto.migrate
